In [2]:
import pandas as pd

In [8]:
df = pd.read_csv("classification_multivar.csv",sep="\t")

df

,loader,dataset,auto,\tau_{temp},\tau_{inst},\lambda,acc,auprc
0,UEA,Epilepsy,y,0.200000,0,0.5,0.949275,0.964108
1,UEA,Epilepsy,n,0.000000,0,0.5,0.963768,0.977551
2,UEA,Epilepsy,n,0.200000,0,0.5,0.956522,0.966767
3,UEA,Epilepsy,n,0.500000,0,0.5,0.963768,0.968846
4,UEA,Epilepsy,n,1.000000,0,0.5,0.956522,0.975602
5,UEA,Epilepsy,n,2.000000,0,0.5,0.963768,0.975241
6,UEA,Epilepsy,n,4.000000,0,0.5,0.963768,0.977202
7,UEA,SelfRegulationSCP2,y,0.035088,0,0.5,0.533333,0.543642
8,UEA,SelfRegulationSCP2,n,0.000000,0,0.5,0.550000,0.543534
9,UEA,SelfRegulationSCP2,n,0.200000,0,0.5,0.550000,0.563728
10,UEA,SelfRegulationSCP2,n,0.500000,0,0.5,0.522222,0.542523
11,UEA,SelfRegulationSCP2,n,1.000000,0,0.5,0.544444,0.554011
12,UEA,SelfRegulationSCP2,n,2.000000,0,0.5,0.566667,0.539971
13,UEA,SelfRegulationSCP2,n,4.000000,0,0.5,0.533333,0.551486
14,UEA,Libras,y,0.666667,0,0.5,0.872222,0.886931
15,UEA,Libras,n,0.000000,0,0.5,0.844444,0.863171
16,UEA,Libras,n,0.200000,0,0.5,0.861111,0.877519
17,UEA,Libras,n,0.500000,0,0.5,0.866667,0.882753
18,UEA,Libras,n,1.000000,0,0.5,0.866667,0.882337
19,UEA,Libras,n,2.000000,0,0.5,0.850000,0.876757
20,UEA,Libras,n,4.000000,0,0.5,0.838889,0.863804
21,UEA,RacketSports,n,0.000000,0,0.5,0.855263,0.871569
22,UEA,RacketSports,n,0.200000,0,0.5,0.855263,0.880320
23,UEA,RacketSports,n,0.500000,0,0.5,0.861842,0.896269
24,UEA,RacketSports,n,1.000000,0,0.5,0.855263,0.891292
25,UEA,RacketSports,n,2.000000,0,0.5,0.842105,0.874719
26,UEA,RacketSports,n,4.000000,0,0.5,0.848684,0.870928
27,UEA,Epilepsy,y,0.200000,0,0.5,0.949275,0.964108
28,UEA,SelfRegulationSCP2,y,0.035088,0,0.5,0.533333,0.543642
29,UEA,Libras,y,0.666667,0,0.5,0.872222,0.886931

In [9]:
df_tmp_forecast_forecast = df.drop(columns=["loader","\\lambda","\\tau_{inst}"])

# rename if the name exists in the dictionary
name_map= { i:"$"+i+"$" for i in ["\\tau_{temp}","\\tau_{inst}","\\lambda"]}
df_tmp_forecast_forecast.rename(columns = name_map,inplace=True)
df_tmp_forecast_forecast
df_tmp_forecast_forecast.style.format({"\\tau_{temp}": "{:,.2f}".format,"\\tau_{inst}": "{:,.2f}".format,}, precision=3)  
#print(df_tmp_forecast_forecast.to_latex(index=False,
#                  formatters={"\\tau_{temp}": "{:,.2f}".format,"\\tau_{inst}": "{:,.2f}".format,},
#                  float_format="{:,.3f}".format
#))

In [26]:
df_forecast = pd.read_csv("forecast_csv_univar.csv",sep="\t")
df

,loader,dataset,auto,\tau_{temp},\tau_{inst},\lambda,acc,auprc
0,UCR,Chinatown,y,0.666667,0,0.5,0.976676,0.996991
1,UCR,Chinatown,n,0.000000,0,0.5,0.970845,0.996028
2,UCR,Chinatown,n,0.200000,0,0.5,0.982507,0.997688
3,UCR,Chinatown,n,0.500000,0,0.5,0.976676,0.997010
4,UCR,Chinatown,n,1.000000,0,0.5,0.973761,0.996809
5,UCR,Chinatown,n,2.000000,0,0.5,0.973761,0.996378
6,UCR,Chinatown,n,4.000000,0,0.5,0.970845,0.996038
7,UCR,Coffee,y,0.400000,0,0.5,1.000000,1.000000
8,UCR,Coffee,n,0.000000,0,0.5,1.000000,1.000000
9,UCR,Coffee,n,0.200000,0,0.5,1.000000,1.000000
10,UCR,Coffee,n,0.500000,0,0.5,1.000000,1.000000
11,UCR,Coffee,n,1.000000,0,0.5,1.000000,1.000000
12,UCR,Coffee,n,2.000000,0,0.5,1.000000,1.000000
13,UCR,Coffee,n,4.000000,0,0.5,1.000000,1.000000
14,UCR,Computers,y,0.333333,0,0.5,0.612000,0.681972
15,UCR,Computers,n,0.000000,0,0.5,0.664000,0.701030
16,UCR,Computers,n,0.200000,0,0.5,0.644000,0.650311
17,UCR,Computers,n,0.500000,0,0.5,0.624000,0.693528
18,UCR,Computers,n,1.000000,0,0.5,0.648000,0.716955
19,UCR,Computers,n,2.000000,0,0.5,0.652000,0.690479
20,UCR,Computers,n,4.000000,0,0.5,0.656000,0.700706
21,UCR,DiatomSizeReduction,y,1.000000,0,0.5,0.983660,0.997821
22,UCR,DiatomSizeReduction,n,0.000000,0,0.5,0.986928,0.992337
23,UCR,DiatomSizeReduction,n,0.200000,0,0.5,0.980392,0.999754
24,UCR,DiatomSizeReduction,n,0.500000,0,0.5,0.980392,0.995154
25,UCR,DiatomSizeReduction,n,1.000000,0,0.5,0.983660,0.997858
26,UCR,DiatomSizeReduction,n,2.000000,0,0.5,0.983660,0.991559
27,UCR,DiatomSizeReduction,n,4.000000,0,0.5,0.980392,0.994436

In [31]:

df_tmp_forecast_forecast = df_forecast.drop(columns=["loader","\\tau_{inst}","\\lambda"])
df_tmp_forecast_forecast = df_tmp_forecast_forecast.drop(columns=df_tmp_forecast_forecast.columns[df_tmp_forecast_forecast.columns.str.contains("{r")])
df_tmp_forecast_forecast = df_tmp_forecast_forecast.drop(columns=df_tmp_forecast_forecast.columns[df_tmp_forecast_forecast.columns.str.contains("MAE")])


# rename if the name exists in the dictionary
name_map = { i:"$"+i.replace("n-","")+"$" for i in df_tmp_forecast_forecast.columns[df_tmp_forecast_forecast.columns.str.contains("n-")]}
name_map.update({ i:"$"+i+"$" for i in ["\\tau_{temp}","\\tau_{inst}","\\lambda"]})
df_tmp_forecast_forecast.rename(columns = name_map,inplace=True)

#name_map = { i:"$"+i+"$" for i in df_tmp_forecast_forecast.columns}
print(df_tmp_forecast_forecast.to_latex(index=False,
                  formatters={"\\tau_{temp}": "{:,.2f}".format,"\\tau_{inst}": "{:,.2f}".format,},
                  float_format="{:,.3f}".format
))

\begin{tabular}{llrrrrrr}
\toprule
dataset & auto_s & $\tau_{temp}$ & $MSE_{24}$ & $MSE_{48}$ & $MSE_{168}$ & $MSE_{336}$ & $MSE_{720}$ \\
\midrule
ETTh1 & n & 0.000 & 0.042 & 0.063 & 0.120 & 0.140 & 0.162 \\
ETTh1 & y & 0.400 & 0.045 & 0.077 & 0.142 & 0.155 & 0.177 \\
ETTh1 & n & 0.200 & 0.044 & 0.073 & 0.144 & 0.161 & 0.190 \\
ETTh1 & n & 0.500 & 0.045 & 0.077 & 0.144 & 0.157 & 0.173 \\
ETTh1 & n & 1.000 & 0.045 & 0.063 & 0.126 & 0.144 & 0.168 \\
ETTh1 & n & 2.000 & 0.044 & 0.062 & 0.121 & 0.140 & 0.163 \\
ETTh1 & n & 4.000 & 0.042 & 0.063 & 0.121 & 0.141 & 0.163 \\
ETTh2 & n & 0.000 & 0.093 & 0.126 & 0.194 & 0.199 & 0.212 \\
ETTh2 & y & 0.333 & 0.095 & 0.129 & 0.193 & 0.207 & 0.222 \\
ETTh2 & n & 0.200 & 0.100 & 0.133 & 0.196 & 0.209 & 0.222 \\
ETTh2 & n & 0.500 & 0.094 & 0.129 & 0.199 & 0.208 & 0.223 \\
ETTh2 & n & 1.000 & 0.092 & 0.126 & 0.197 & 0.203 & 0.217 \\
ETTh2 & n & 2.000 & 0.092 & 0.123 & 0.191 & 0.197 & 0.211 \\
ETTh2 & n & 4.000 & 0.094 & 0.125 & 0.195 & 0.200 & 0.213 \\
ETTh1 & y & 0.400 & 0.045 & 0.077 & 0.142 & 0.155 & 0.177 \\
ETTh1 & n & 0.200 & 0.044 & 0.073 & 0.144 & 0.161 & 0.189 \\
ETTh1 & n & 0.500 & 0.045 & 0.077 & 0.144 & 0.157 & 0.173 \\
ETTh1 & n & 1.000 & 0.045 & 0.063 & 0.126 & 0.144 & 0.168 \\
ETTh1 & n & 2.000 & 0.044 & 0.062 & 0.121 & 0.140 & 0.163 \\
ETTh1 & n & 4.000 & 0.042 & 0.063 & 0.121 & 0.141 & 0.163 \\
ETTh1 & y & 0.400 & 0.045 & 0.077 & 0.142 & 0.155 & 0.177 \\
ETTh1 & n & 0.200 & 0.044 & 0.073 & 0.144 & 0.161 & 0.190 \\
ETTh1 & n & 0.500 & 0.045 & 0.077 & 0.144 & 0.157 & 0.174 \\
ETTh1 & n & 1.000 & 0.045 & 0.063 & 0.126 & 0.144 & 0.168 \\
ETTh1 & n & 2.000 & 0.045 & 0.062 & 0.121 & 0.140 & 0.163 \\
ETTh1 & n & 4.000 & 0.042 & 0.063 & 0.122 & 0.142 & 0.164 \\
ETTh1 & y & 0.400 & 0.045 & 0.077 & 0.142 & 0.155 & 0.177 \\
ETTh1 & n & 0.200 & 0.044 & 0.073 & 0.144 & 0.161 & 0.189 \\
ETTh1 & n & 0.500 & 0.045 & 0.077 & 0.144 & 0.157 & 0.173 \\
ETTh1 & n & 1.000 & 0.045 & 0.063 & 0.126 & 0.144 & 0.168 \\
ETTh1 & n & 2.000 & 0.045 & 0.062 & 0.122 & 0.141 & 0.164 \\
ETTh1 & n & 4.000 & 0.042 & 0.063 & 0.121 & 0.141 & 0.163 \\
ETTh1 & y & 0.400 & 0.045 & 0.077 & 0.142 & 0.155 & 0.176 \\
ETTh1 & n & 0.200 & 0.044 & 0.073 & 0.144 & 0.161 & 0.189 \\
ETTh1 & n & 0.500 & 0.045 & 0.078 & 0.144 & 0.157 & 0.173 \\
ETTh1 & n & 1.000 & 0.045 & 0.063 & 0.126 & 0.144 & 0.168 \\
ETTh1 & n & 2.000 & 0.045 & 0.062 & 0.121 & 0.140 & 0.163 \\
ETTh1 & n & 4.000 & 0.042 & 0.063 & 0.121 & 0.141 & 0.163 \\
ETTh1 & y & 0.400 & 0.045 & 0.077 & 0.142 & 0.155 & 0.177 \\
ETTh1 & n & 0.200 & 0.044 & 0.073 & 0.144 & 0.161 & 0.190 \\
ETTh1 & n & 0.500 & 0.044 & 0.077 & 0.144 & 0.156 & 0.174 \\
ETTh1 & n & 1.000 & 0.044 & 0.063 & 0.125 & 0.144 & 0.167 \\
ETTh1 & n & 2.000 & 0.045 & 0.062 & 0.121 & 0.140 & 0.163 \\
ETTh1 & n & 4.000 & 0.042 & 0.063 & 0.121 & 0.141 & 0.163 \\
\bottomrule
\end{tabular}

In [ ]:
df_tmp_forecast_forecast.style.format({"\\tau_{temp}": "{:,.2f}".format,"\\tau_{inst}": "{:,.2f}".format,}, precision=3)