In [35]:
import pandas as pd

In [38]:
df = pd.read_csv("classification.csv",sep="\t")

df

,loader,dataset,auto,\tau_{temp},\tau_{inst},\lambda,acc,auprc
0,UCR,Chinatown,y,0.666667,0,0.5,0.976676,0.996991
1,UCR,Chinatown,n,0.000000,0,0.5,0.970845,0.996028
2,UCR,Chinatown,n,0.200000,0,0.5,0.982507,0.997688
3,UCR,Chinatown,n,0.500000,0,0.5,0.976676,0.997010
4,UCR,Chinatown,n,1.000000,0,0.5,0.973761,0.996809
5,UCR,Chinatown,n,2.000000,0,0.5,0.973761,0.996378
6,UCR,Chinatown,n,4.000000,0,0.5,0.970845,0.996038
7,UCR,Coffee,y,0.400000,0,0.5,1.000000,1.000000
8,UCR,Coffee,n,0.000000,0,0.5,1.000000,1.000000
9,UCR,Coffee,n,0.200000,0,0.5,1.000000,1.000000
10,UCR,Coffee,n,0.500000,0,0.5,1.000000,1.000000
11,UCR,Coffee,n,1.000000,0,0.5,1.000000,1.000000
12,UCR,Coffee,n,2.000000,0,0.5,1.000000,1.000000
13,UCR,Coffee,n,4.000000,0,0.5,1.000000,1.000000
14,UCR,Computers,y,0.333333,0,0.5,0.612000,0.681972
15,UCR,Computers,n,0.000000,0,0.5,0.664000,0.701030
16,UCR,Computers,n,0.200000,0,0.5,0.644000,0.650311
17,UCR,Computers,n,0.500000,0,0.5,0.624000,0.693528
18,UCR,Computers,n,1.000000,0,0.5,0.648000,0.716955
19,UCR,Computers,n,2.000000,0,0.5,0.652000,0.690479
20,UCR,Computers,n,4.000000,0,0.5,0.656000,0.700706
21,UCR,DiatomSizeReduction,y,1.000000,0,0.5,0.983660,0.997821
22,UCR,DiatomSizeReduction,n,0.000000,0,0.5,0.986928,0.992337
23,UCR,DiatomSizeReduction,n,0.200000,0,0.5,0.980392,0.999754
24,UCR,DiatomSizeReduction,n,0.500000,0,0.5,0.980392,0.995154
25,UCR,DiatomSizeReduction,n,1.000000,0,0.5,0.983660,0.997858
26,UCR,DiatomSizeReduction,n,2.000000,0,0.5,0.983660,0.991559
27,UCR,DiatomSizeReduction,n,4.000000,0,0.5,0.980392,0.994436

In [39]:
df_tmp_forecast_forecast = df.drop(columns=["loader","\\lambda","\\tau_{inst}"])

# rename if the name exists in the dictionary
name_map= { i:"$"+i+"$" for i in ["\\tau_{temp}","\\tau_{inst}","\\lambda"]}
df_tmp_forecast_forecast.rename(columns = name_map,inplace=True)

print(df_tmp_forecast_forecast.to_latex(index=False,
                  formatters={"\\tau_{temp}": "{:,.2f}".format,"\\tau_{inst}": "{:,.2f}".format,},
                  float_format="{:,.3f}".format
))

\begin{tabular}{llrrr}
\toprule
dataset & auto & $\tau_{temp}$ & acc & auprc \\
\midrule
Chinatown & y & 0.667 & 0.977 & 0.997 \\
Chinatown & n & 0.000 & 0.971 & 0.996 \\
Chinatown & n & 0.200 & 0.983 & 0.998 \\
Chinatown & n & 0.500 & 0.977 & 0.997 \\
Chinatown & n & 1.000 & 0.974 & 0.997 \\
Chinatown & n & 2.000 & 0.974 & 0.996 \\
Chinatown & n & 4.000 & 0.971 & 0.996 \\
Coffee & y & 0.400 & 1.000 & 1.000 \\
Coffee & n & 0.000 & 1.000 & 1.000 \\
Coffee & n & 0.200 & 1.000 & 1.000 \\
Coffee & n & 0.500 & 1.000 & 1.000 \\
Coffee & n & 1.000 & 1.000 & 1.000 \\
Coffee & n & 2.000 & 1.000 & 1.000 \\
Coffee & n & 4.000 & 1.000 & 1.000 \\
Computers & y & 0.333 & 0.612 & 0.682 \\
Computers & n & 0.000 & 0.664 & 0.701 \\
Computers & n & 0.200 & 0.644 & 0.650 \\
Computers & n & 0.500 & 0.624 & 0.694 \\
Computers & n & 1.000 & 0.648 & 0.717 \\
Computers & n & 2.000 & 0.652 & 0.690 \\
Computers & n & 4.000 & 0.656 & 0.701 \\
DiatomSizeReduction & y & 1.000 & 0.984 & 0.998 \\
DiatomSizeReduction & n & 0.000 & 0.987 & 0.992 \\
DiatomSizeReduction & n & 0.200 & 0.980 & 1.000 \\
DiatomSizeReduction & n & 0.500 & 0.980 & 0.995 \\
DiatomSizeReduction & n & 1.000 & 0.984 & 0.998 \\
DiatomSizeReduction & n & 2.000 & 0.984 & 0.992 \\
DiatomSizeReduction & n & 4.000 & 0.980 & 0.994 \\
\bottomrule
\end{tabular}

In [26]:
df_forecast = pd.read_csv("forecast_csv_univar.csv",sep="\t")
df

,loader,dataset,auto,\tau_{temp},\tau_{inst},\lambda,acc,auprc
0,UCR,Chinatown,y,0.666667,0,0.5,0.976676,0.996991
1,UCR,Chinatown,n,0.000000,0,0.5,0.970845,0.996028
2,UCR,Chinatown,n,0.200000,0,0.5,0.982507,0.997688
3,UCR,Chinatown,n,0.500000,0,0.5,0.976676,0.997010
4,UCR,Chinatown,n,1.000000,0,0.5,0.973761,0.996809
5,UCR,Chinatown,n,2.000000,0,0.5,0.973761,0.996378
6,UCR,Chinatown,n,4.000000,0,0.5,0.970845,0.996038
7,UCR,Coffee,y,0.400000,0,0.5,1.000000,1.000000
8,UCR,Coffee,n,0.000000,0,0.5,1.000000,1.000000
9,UCR,Coffee,n,0.200000,0,0.5,1.000000,1.000000
10,UCR,Coffee,n,0.500000,0,0.5,1.000000,1.000000
11,UCR,Coffee,n,1.000000,0,0.5,1.000000,1.000000
12,UCR,Coffee,n,2.000000,0,0.5,1.000000,1.000000
13,UCR,Coffee,n,4.000000,0,0.5,1.000000,1.000000
14,UCR,Computers,y,0.333333,0,0.5,0.612000,0.681972
15,UCR,Computers,n,0.000000,0,0.5,0.664000,0.701030
16,UCR,Computers,n,0.200000,0,0.5,0.644000,0.650311
17,UCR,Computers,n,0.500000,0,0.5,0.624000,0.693528
18,UCR,Computers,n,1.000000,0,0.5,0.648000,0.716955
19,UCR,Computers,n,2.000000,0,0.5,0.652000,0.690479
20,UCR,Computers,n,4.000000,0,0.5,0.656000,0.700706
21,UCR,DiatomSizeReduction,y,1.000000,0,0.5,0.983660,0.997821
22,UCR,DiatomSizeReduction,n,0.000000,0,0.5,0.986928,0.992337
23,UCR,DiatomSizeReduction,n,0.200000,0,0.5,0.980392,0.999754
24,UCR,DiatomSizeReduction,n,0.500000,0,0.5,0.980392,0.995154
25,UCR,DiatomSizeReduction,n,1.000000,0,0.5,0.983660,0.997858
26,UCR,DiatomSizeReduction,n,2.000000,0,0.5,0.983660,0.991559
27,UCR,DiatomSizeReduction,n,4.000000,0,0.5,0.980392,0.994436

In [31]:

df_tmp_forecast_forecast = df_forecast.drop(columns=["loader","\\tau_{inst}","\\lambda"])
df_tmp_forecast_forecast = df_tmp_forecast_forecast.drop(columns=df_tmp_forecast_forecast.columns[df_tmp_forecast_forecast.columns.str.contains("{r")])
df_tmp_forecast_forecast = df_tmp_forecast_forecast.drop(columns=df_tmp_forecast_forecast.columns[df_tmp_forecast_forecast.columns.str.contains("MAE")])


# rename if the name exists in the dictionary
name_map = { i:"$"+i.replace("n-","")+"$" for i in df_tmp_forecast_forecast.columns[df_tmp_forecast_forecast.columns.str.contains("n-")]}
name_map.update({ i:"$"+i+"$" for i in ["\\tau_{temp}","\\tau_{inst}","\\lambda"]})
df_tmp_forecast_forecast.rename(columns = name_map,inplace=True)

#name_map = { i:"$"+i+"$" for i in df_tmp_forecast_forecast.columns}
print(df_tmp_forecast_forecast.to_latex(index=False,
                  formatters={"\\tau_{temp}": "{:,.2f}".format,"\\tau_{inst}": "{:,.2f}".format,},
                  float_format="{:,.3f}".format
))

\begin{tabular}{llrrrrrr}
\toprule
dataset & auto_s & $\tau_{temp}$ & $MSE_{24}$ & $MSE_{48}$ & $MSE_{168}$ & $MSE_{336}$ & $MSE_{720}$ \\
\midrule
ETTh1 & n & 0.000 & 0.042 & 0.063 & 0.120 & 0.140 & 0.162 \\
ETTh1 & y & 0.400 & 0.045 & 0.077 & 0.142 & 0.155 & 0.177 \\
ETTh1 & n & 0.200 & 0.044 & 0.073 & 0.144 & 0.161 & 0.190 \\
ETTh1 & n & 0.500 & 0.045 & 0.077 & 0.144 & 0.157 & 0.173 \\
ETTh1 & n & 1.000 & 0.045 & 0.063 & 0.126 & 0.144 & 0.168 \\
ETTh1 & n & 2.000 & 0.044 & 0.062 & 0.121 & 0.140 & 0.163 \\
ETTh1 & n & 4.000 & 0.042 & 0.063 & 0.121 & 0.141 & 0.163 \\
ETTh2 & n & 0.000 & 0.093 & 0.126 & 0.194 & 0.199 & 0.212 \\
ETTh2 & y & 0.333 & 0.095 & 0.129 & 0.193 & 0.207 & 0.222 \\
ETTh2 & n & 0.200 & 0.100 & 0.133 & 0.196 & 0.209 & 0.222 \\
ETTh2 & n & 0.500 & 0.094 & 0.129 & 0.199 & 0.208 & 0.223 \\
ETTh2 & n & 1.000 & 0.092 & 0.126 & 0.197 & 0.203 & 0.217 \\
ETTh2 & n & 2.000 & 0.092 & 0.123 & 0.191 & 0.197 & 0.211 \\
ETTh2 & n & 4.000 & 0.094 & 0.125 & 0.195 & 0.200 & 0.213 \\
ETTh1 & y & 0.400 & 0.045 & 0.077 & 0.142 & 0.155 & 0.177 \\
ETTh1 & n & 0.200 & 0.044 & 0.073 & 0.144 & 0.161 & 0.189 \\
ETTh1 & n & 0.500 & 0.045 & 0.077 & 0.144 & 0.157 & 0.173 \\
ETTh1 & n & 1.000 & 0.045 & 0.063 & 0.126 & 0.144 & 0.168 \\
ETTh1 & n & 2.000 & 0.044 & 0.062 & 0.121 & 0.140 & 0.163 \\
ETTh1 & n & 4.000 & 0.042 & 0.063 & 0.121 & 0.141 & 0.163 \\
ETTh1 & y & 0.400 & 0.045 & 0.077 & 0.142 & 0.155 & 0.177 \\
ETTh1 & n & 0.200 & 0.044 & 0.073 & 0.144 & 0.161 & 0.190 \\
ETTh1 & n & 0.500 & 0.045 & 0.077 & 0.144 & 0.157 & 0.174 \\
ETTh1 & n & 1.000 & 0.045 & 0.063 & 0.126 & 0.144 & 0.168 \\
ETTh1 & n & 2.000 & 0.045 & 0.062 & 0.121 & 0.140 & 0.163 \\
ETTh1 & n & 4.000 & 0.042 & 0.063 & 0.122 & 0.142 & 0.164 \\
ETTh1 & y & 0.400 & 0.045 & 0.077 & 0.142 & 0.155 & 0.177 \\
ETTh1 & n & 0.200 & 0.044 & 0.073 & 0.144 & 0.161 & 0.189 \\
ETTh1 & n & 0.500 & 0.045 & 0.077 & 0.144 & 0.157 & 0.173 \\
ETTh1 & n & 1.000 & 0.045 & 0.063 & 0.126 & 0.144 & 0.168 \\
ETTh1 & n & 2.000 & 0.045 & 0.062 & 0.122 & 0.141 & 0.164 \\
ETTh1 & n & 4.000 & 0.042 & 0.063 & 0.121 & 0.141 & 0.163 \\
ETTh1 & y & 0.400 & 0.045 & 0.077 & 0.142 & 0.155 & 0.176 \\
ETTh1 & n & 0.200 & 0.044 & 0.073 & 0.144 & 0.161 & 0.189 \\
ETTh1 & n & 0.500 & 0.045 & 0.078 & 0.144 & 0.157 & 0.173 \\
ETTh1 & n & 1.000 & 0.045 & 0.063 & 0.126 & 0.144 & 0.168 \\
ETTh1 & n & 2.000 & 0.045 & 0.062 & 0.121 & 0.140 & 0.163 \\
ETTh1 & n & 4.000 & 0.042 & 0.063 & 0.121 & 0.141 & 0.163 \\
ETTh1 & y & 0.400 & 0.045 & 0.077 & 0.142 & 0.155 & 0.177 \\
ETTh1 & n & 0.200 & 0.044 & 0.073 & 0.144 & 0.161 & 0.190 \\
ETTh1 & n & 0.500 & 0.044 & 0.077 & 0.144 & 0.156 & 0.174 \\
ETTh1 & n & 1.000 & 0.044 & 0.063 & 0.125 & 0.144 & 0.167 \\
ETTh1 & n & 2.000 & 0.045 & 0.062 & 0.121 & 0.140 & 0.163 \\
ETTh1 & n & 4.000 & 0.042 & 0.063 & 0.121 & 0.141 & 0.163 \\
\bottomrule
\end{tabular}